name: Build and Release Wheels

on:
  release:
    types: [published]

jobs:
  build_wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['9', '10', '11', '12', '13']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.${{ matrix.python-version }}

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Maturin
        run: |
          python -m pip install --upgrade pip
          pip install maturin

      - name: Build wheels
        run: python3 -m pip wheel .

      - name: List wheels
        run: |
          ls -l .

      - name: Upload wheels to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./nvfaidx-0.0.1-cp3${{ matrix.python-version }}-cp3${{ matrix.python-version }}-linux_x86_64.whl  # Standard relative path
          asset_name: nvfaidx-0.0.1-cp3${{ matrix.python-version }}-cp3${{ matrix.python-version }}-linux_x86_64.whl
          asset_content_type: application/zip
